name: construction
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=3.6.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  logger: ^2.0.2
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  cached_network_image:
  supabase_flutter: ^2.0.0
  bot_toast: ^4.0.3
  hive: ^2.2.3
  dio: ^5.5.0+1
  iconify_flutter: ^0.0.5
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  firebase_cached_image: ^0.6.1
  carousel_indicator: ^1.0.6
  flutter_animation_progress_bar: ^2.3.1
  intl: ^0.20.2
  syncfusion_flutter_pdf: ^28.2.4
  syncfusion_flutter_signaturepad: ^28.2.4
  path_provider: ^2.0.11
  open_filex: ^4.3.2
  toggle_switch: ^2.0.1
  flutter_typeahead: ^5.2.0
  url_launcher: ^6.3.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

