// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu599fd4E3_2LJYjKW_FbV-vIhZ2BoiaI',
    appId: '1:99173771493:web:67c9b7dabc97a63ffb8c0c',
    messagingSenderId: '99173771493',
    projectId: 'buildmasterv12025',
    authDomain: 'buildmasterv12025.firebaseapp.com',
    storageBucket: 'buildmasterv12025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwdh8_5mwjM9NWGIS-TVenmJxWTXFkmpM',
    appId: '1:99173771493:android:de4e8634eb014148fb8c0c',
    messagingSenderId: '99173771493',
    projectId: 'buildmasterv12025',
    storageBucket: 'buildmasterv12025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ35bEPdplQ7WbmHDFvGNNpRkKoW7gfUM',
    appId: '1:99173771493:ios:b083e9f39a785694fb8c0c',
    messagingSenderId: '99173771493',
    projectId: 'buildmasterv12025',
    storageBucket: 'buildmasterv12025.firebasestorage.app',
    iosBundleId: 'com.fyp.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ35bEPdplQ7WbmHDFvGNNpRkKoW7gfUM',
    appId: '1:99173771493:ios:b083e9f39a785694fb8c0c',
    messagingSenderId: '99173771493',
    projectId: 'buildmasterv12025',
    storageBucket: 'buildmasterv12025.firebasestorage.app',
    iosBundleId: 'com.fyp.construction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu599fd4E3_2LJYjKW_FbV-vIhZ2BoiaI',
    appId: '1:99173771493:web:6fc04cfc55ccfd3efb8c0c',
    messagingSenderId: '99173771493',
    projectId: 'buildmasterv12025',
    authDomain: 'buildmasterv12025.firebaseapp.com',
    storageBucket: 'buildmasterv12025.firebasestorage.app',
  );

}